#!/usr/bin/env python3
"""
build_brain.py -- "docker compose for a second brain".

Deterministically assembles an Obsidian vault from committed markdown knowledge
plus a light, dependency-free scan of the repo. No MCP, no LLM, no network -- so
ANY developer or agent can reproduce the same brain with one command:

    python3 second-brain/build_brain.py

Model
-----
  knowledge/   (committed, sanitized)   = SOURCE OF TRUTH  -- edit notes here
  vault/       (generated, gitignored)  = OUTPUT           -- open THIS in Obsidian

The "smart" code-structure notes (call graphs, data flow) are generated by an
agent from the code graph (codebase-memory / Graphify) into knowledge/code/ and
committed, so this deterministic build reproduces them. See AGENTS.md.

This script is repo-agnostic; everything project-specific lives in brain.config.json.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess  # noqa: F401  (used by the graphify adapter path)
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Default route pattern (FastAPI/Flask-class decorators). Override per-repo via
# brain.config.json -> route_scan.patterns (list of regexes, each with 1-2 groups:
# either (method, path) or just (path)). Examples for other stacks:
#   Express:  r'\.(get|post|put|delete|patch)\(\s*["\']([^"\']+)["\']'
#   Flask:    r'@\w+\.route\(\s*["\']([^"\']+)["\']'
#   Spring:   r'@(?:Get|Post|Put|Delete|Patch|Request)Mapping\(\s*["\']([^"\']+)["\']'
_DEFAULT_ROUTE_PATTERNS = [
    r'@\w+\.(get|post|put|delete|patch|websocket)\(\s*["\']([^"\']+)["\']',
]


def load_config() -> dict:
    return json.loads((HERE / "brain.config.json").read_text(encoding="utf-8"))


def note_title(path: Path) -> str:
    """Best display title: YAML `title:`, else first H1, else filename."""
    text = path.read_text(encoding="utf-8", errors="replace")
    m = re.search(r'^title:\s*"?(.+?)"?\s*$', text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return path.stem.replace("-", " ").replace("_", " ").strip()


def wikilink(vault: Path, note: Path, alias: str | None = None) -> str:
    """Vault-relative wikilink without extension, e.g. [[architecture/overview|Overview]]."""
    rel = note.relative_to(vault).with_suffix("").as_posix()
    return f"[[{rel}|{alias}]]" if alias else f"[[{rel}]]"


def clean_vault(vault: Path) -> None:
    """Remove everything the builder manages, but preserve the user's .obsidian settings."""
    if not vault.exists():
        vault.mkdir(parents=True)
        return
    for child in vault.iterdir():
        if child.name == ".obsidian":
            continue
        shutil.rmtree(child) if child.is_dir() else child.unlink()


def copy_knowledge(knowledge: Path, vault: Path) -> list[Path]:
    """Copy knowledge/**/*.md into the vault, preserving structure. Returns copied vault paths."""
    copied: list[Path] = []
    for src in sorted(knowledge.rglob("*.md")):
        rel = src.relative_to(knowledge)
        dst = vault / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)
        copied.append(dst)
    return copied


def scan_routes(cfg: dict, repo: Path, vault: Path) -> Path | None:
    """Dependency-free route scan -> a code-grounded note. Best-effort, language-configurable."""
    rc = cfg.get("route_scan", {})
    if not rc.get("enabled"):
        return None
    patterns = [re.compile(p, re.IGNORECASE) for p in (rc.get("patterns") or _DEFAULT_ROUTE_PATTERNS)]
    seen: set[tuple[str, str]] = set()
    rows: list[tuple[str, str, str]] = []  # method, path, file:line
    files: list[Path] = []
    for g in rc.get("include_globs", ["*.py"]):
        files.extend(repo.glob(g))
    for f in sorted(set(files)):
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except (OSError, ValueError):
            continue
        for i, line in enumerate(text.splitlines(), 1):
            for pat in patterns:
                m = pat.search(line)
                if not m:
                    continue
                groups = m.groups()
                if len(groups) >= 2:
                    method, route = groups[0].upper(), groups[1]
                else:
                    method, route = "ANY", groups[0]
                key = (method, route)
                if key in seen:
                    continue
                seen.add(key)
                rows.append((method, route, f"{f.relative_to(repo).as_posix()}:{i}"))
                break
    if not rows:
        return None
    rows.sort(key=lambda r: (r[1], r[0]))
    out = vault / rc.get("output", "code/routes.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "---", "tags: [code, generated]", "---",
        "# HTTP Routes (auto-scanned)",
        "",
        f"> Regenerated by `build_brain.py` on {date.today().isoformat()} "
        f"from `{repo.name}/`. {len(rows)} routes.",
        "",
        "| Method | Route | Defined in |",
        "| --- | --- | --- |",
    ]
    lines += [f"| `{m}` | `{r}` | `{loc}` |" for m, r, loc in rows]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


def fold_in_graphify(cfg: dict, vault: Path) -> int | None:
    """If Graphify is enabled and a graph exists, export its Obsidian notes into the vault."""
    gcfg = cfg.get("graph_source", {}).get("graphify", {})
    if not gcfg.get("enabled"):
        return None
    if str(HERE) not in sys.path:
        sys.path.insert(0, str(HERE))
    try:
        from graph_sources import graphify as gfx
    except Exception as e:  # pragma: no cover
        print(f"  graphify: adapter import failed ({e})")
        return None
    if not gfx.is_installed():
        print("  graphify: CLI not installed — run: uv tool install graphifyy")
        return None
    out_dir = (HERE / gcfg.get("out_dir", ".graphify")).resolve()
    graph_json = gfx.graph_json_path(out_dir)
    if not graph_json.exists():
        print("  graphify: no graph yet — run second-brain/graphify_refresh.sh to build it")
        return None
    dest = vault / gcfg.get("vault_subdir", "graphify")
    try:
        n = gfx.export_obsidian(graph_json, dest)
    except Exception as e:
        print(f"  graphify: export failed ({e})")
        return None
    print(f"  graphify: {n} code notes -> {dest.relative_to(vault)}/")
    return n


def gen_section_indexes(cfg: dict, vault: Path) -> list[tuple[dict, Path]]:
    """Generate an _index.md MOC per configured section that has notes."""
    made: list[tuple[dict, Path]] = []
    for sec in sorted(cfg["sections"], key=lambda s: s.get("order", 99)):
        sdir = vault / sec["dir"]
        if not sdir.exists():
            continue
        notes = sorted(p for p in sdir.rglob("*.md") if p.name != "_index.md")
        if not notes:
            continue
        idx = sdir / "_index.md"
        lines = [
            "---", f"tags: [moc, {sec['dir']}]", "---",
            f"# {sec['title']}", "",
            f"> {len(notes)} notes. Section index for **{sec['title']}**.", "",
        ]
        for n in notes:
            lines.append(f"- {wikilink(vault, n, note_title(n))}")
        idx.write_text("\n".join(lines) + "\n", encoding="utf-8")
        made.append((sec, idx))
    return made


def gen_home(cfg: dict, vault: Path, sections: list[tuple[dict, Path]],
             graphify_notes: int | None = None) -> Path:
    home = vault / "00-Home.md"
    lines = [
        "---", "tags: [moc, home]", "---",
        f"# {cfg['title']}", "",
        f"> {cfg.get('description', '')}", "",
        f"*Generated {date.today().isoformat()} by `build_brain.py`. "
        "Edit source notes in `second-brain/knowledge/`, not here.*", "",
        "## Map of Content", "",
    ]
    for sec, idx in sections:
        lines.append(f"- **{wikilink(vault, idx, sec['title'])}**")
    if graphify_notes:
        lines += [
            "", "## Code graph (Graphify)",
            f"- {graphify_notes} auto-generated code notes in `graphify/` "
            "(functions, classes, calls, docstrings). Open `graphify/graph.canvas` as an Obsidian Canvas.",
            "- Rebuild the graph: `second-brain/graphify_refresh.sh`.",
        ]
    lines += [
        "", "---",
        "## How to use this brain",
        "- **Browse**: open the graph view; start from a section index above.",
        "- **Ask (your agent)**: the Obsidian MCP lets your agent read/write these notes.",
        "- **Ask (in Obsidian)**: Smart Connections / Copilot chat over the vault.",
        "- **Refresh code notes**: see `second-brain/AGENTS.md`.",
    ]
    home.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return home


def main() -> int:
    cfg = load_config()
    knowledge = (HERE / cfg["knowledge_dir"]).resolve()
    vault = (HERE / cfg["vault_dir"]).resolve()
    repo = (HERE / cfg.get("repo_root", "..")).resolve()

    if not knowledge.exists():
        print(f"! knowledge dir not found: {knowledge}", file=sys.stderr)
        return 1

    print(f"Building '{cfg['title']}'")
    print(f"  source : {knowledge}")
    print(f"  output : {vault}")

    clean_vault(vault)
    copied = copy_knowledge(knowledge, vault)
    print(f"  copied : {len(copied)} knowledge notes")

    route_note = scan_routes(cfg, repo, vault)
    if route_note:
        print(f"  routes : {route_note.relative_to(vault)}")

    gfx_notes = fold_in_graphify(cfg, vault)

    sections = gen_section_indexes(cfg, vault)
    print(f"  MOCs   : {len(sections)} section indexes")

    gen_home(cfg, vault, sections, gfx_notes)
    total = len(list(vault.rglob("*.md")))
    print(f"  home   : 00-Home.md")
    print(f"Done. Vault has {total} notes. Open '{vault}' in Obsidian.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
